elastic_host: 192.168.1.40
elastic_port: 9200

kibana_host: 192.168.1.40
kibana_port: 5601

elastic_protocol: http

filebeat_http_port: 5067
auditbeat_http_port: 5068
heartbeat_http_port: 5069
packetbeat_http_port: 5070

web_server_1: 192.168.2.28
web_server_2: 192.168.2.29